### ISSUE TITLE
Inline/In-Application Help

### ISSUE THREAD

**Issue by MCOfficer** [shitwolfymakes/Endless-Sky-Mission-Builder#2]
Right now, the builder is only linking to the wiki page. Since it is geared towards less experienced users, however, it would be ideal to have a question mark button next to each field that gives a short explanation on click/hover.

**Comment by shitwolfymakes** [comment]
Given that implementing that requires digging through through the centerFrame, which was built by hand, that's going to need to wait. The singleton I built to place stuff on the TriggerWindow will be leveraged to replace the hardcoded centerFrame gui in Beta 3

**Comment by MCOfficer** [comment]
it is a longterm suggestion, but it doesn't have to strictly change the frame the button is in, it could just be a mouseover tooltip that's spawned on top. i agree that it can wait, though.

**Comment by shitwolfymakes** [comment]
To get it to display text when you hover over, I'd need to add that hook to every widget I want to add help text to. It'll be much easier to pass it the help text into a builder singleton
