### ISSUE TITLE
ESMB fails to start on Debian 10 'buster'

### ISSUE THREAD

**Issue by StefanSchroeder** [shitwolfymakes/Endless-Sky-Mission-Builder#20]
I ran the build.sh script to install the dependencies. 
Lacking installation instructions I tried out different things. The most promising seemed to be to run 'ESMB-ubuntu-amd64-pythoninstaller'. But this yields:

```
[34151] Failed to execute script ESMB
Traceback (most recent call last):
  File "src/ESMB.py", line 24, in <module>
    from src.model import Mission
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "src/__init__.py", line 9, in <module>
    from .ESMB import ESMB
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "src/ESMB.py", line 25, in <module>
    from src.gui.GUI import GUI
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "src/gui/__init__.py", line 8, in <module>
    from .GUI import GUI
  File "/usr/local/lib/python3.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "src/gui/GUI.py", line 16, in <module>
    import src.gui.editor as editor
ImportError: cannot import name 'editor' from '<unknown module name>' (unknown location)

```

Please advise.

**Comment by MCOfficer** [comment]
The build.sh is for CI, it may not work for personal builds. Just install Python3, run `pip3 install -r requirements.txt` to install dependencies, then run src/ESMB.py

Alternatively, you can download a build from the latest release: https://github.com/shitwolfymakes/Endless-Sky-Mission-Builder/releases/tag/v0.4

**Comment by StefanSchroeder** [comment]
Trying the first option fails as well. The pip3 command runs through with:
Requirement already satisfied: ttkthemes in /home/debian/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2.4.0)
Requirement already satisfied: pillow in /home/debian/.local/lib/python3.7/site-packages (from ttkthemes->-r requirements.txt (line 1)) (7.0.0)

which is good.

But running src/ESMB.py results in:

Traceback (most recent call last):
  File "src/ESMB.py", line 24, in <module>
    from src.model import Mission
ModuleNotFoundError: No module named 'src'

**Comment by StefanSchroeder** [comment]
Running the latest release works.

**Comment by MCOfficer** [comment]
> But running src/ESMB.py results in:
> 
> Traceback (most recent call last):
> File "src/ESMB.py", line 24, in
> from src.model import Mission
> ModuleNotFoundError: No module named 'src'

can confirm that. might wanna add a `__main__.py` so one can just `python3 -m src/` @shitwolfymakes

**Comment by shitwolfymakes** [comment]
@MCOfficer If you could test that and get it working, as well as test how it builds, that'd be really helpful. I've never been able to get the build stuff working properly

**Comment by MCOfficer** [comment]
It's not about the build, intriguingly, once built it runs fine. I'll give it a try though.

**Comment by shitwolfymakes** [comment]
Since the built exe runs fine, I'm going to close this. ESMB is only intended to be run from source during development, so use Pycharm for that.
