### ISSUE TITLE
Moving current CI/CD into Github Actions

### ISSUE THREAD

**Issue by shitwolfymakes** [shitwolfymakes/Endless-Sky-Mission-Builder#21]
**Is your feature request related to a problem? Please describe.**
Currently, our CI/CD is done through a 3rd party, because Actions didn't exist at the time. Now that it does, it's more efficient to do things here.

**Describe the solution you'd like**
- [ ] Each time a push is made in the `indev` branch, it should build an executable for windows, linux, and macOS.
- [ ] Each time a push is made to `master`, it should also trigger a build.
- [ ] Each time there is a release, it should trigger a build from master, and attach the executables to the newest release

Testing can be added later, as I need to update my tests so they don't constantly break

**Describe alternatives you've considered**
We have AppVeyor, but it's 3rd-party and only builds for windows and linux

**Additional context**
@MCOfficer has handled AppVeyor pipeline for this, and set up the Actions pipeline for Endless Sky, so I'll assign this to them

**Comment by MCOfficer** [comment]
> ...so I'll assign this to them

\> doesn't assign

> ... it should build an executable for windows, linux, and macOS.

i can't test or vouch for macOS. I believe you have a mac, so if you can give me instructions on how to get a working executable there, i can add that, but otherwise i'll leave it open.

**Comment by shitwolfymakes** [comment]
Huh, I couldn't see you under the "Assignees" button until you commented. I even looked for you earlier.

I can certainly try! By test I just mean run the executable in the build environment once it's built, if that's possible. I had to drop macOS support after the binary kept crashing my laptop

**Comment by shitwolfymakes** [comment]
Closing this, as it is superseded by #27
