### ISSUE TITLE
No module named 'src'

### ISSUE THREAD

**Issue by Harald-Berghoff** [shitwolfymakes/Endless-Sky-Mission-Builder#23]
**Describe the bug**
When starting the mission builder on Fedora 33, it fails to import the modules. This issues seems to be mentioned briefly in #20, but not solved. 

The error message been reported is:
```
$ python src/ESMB.py
Traceback (most recent call last):
  File "/home/username/Endless-Sky-Mission-Builder-master/src/ESMB.py", line 24, in <module>
    from src.model import Mission
ModuleNotFoundError: No module named 'src'
```

**To Reproduce**
1. Download the master branch as an archive
2. Extract the archive into your home dir
3. open a terminal 
4. go to extracted archive (`cd ~/Endless-Sky-Mission-Builder-master`)
5. start the mission builder (`python src/ESMB.py`)

**Expected behavior**
the mission builder should start, but not report errors related to module import of included modules

**Logs**
No log has been produced

**Desktop (please complete the following information):**
 - OS: Fedora Linux 33
 - Using the master branch sources
 - Not able to test on other OS (no other installed)

**Additional context**
I have checked on the code and the issue at hand is that the import mechanics of python has been changed between 2.7 and newer versions. I am having Python 3.9 installed (Python 3.9.1 (default, Dec  8 2020, 00:00:00) )

Changing into the src dir and starting ESMB.py results in this error:
```
Traceback (most recent call last):
  File "/home/username/Endless-Sky-Mission-Builder-master/src/ESMB.py", line 24, in <module>
    from model import Mission
  File "/home/username/Endless-Sky-Mission-Builder-master/src/model/__init__.py", line 12, in <module>
    from .Mission import Mission
  File "/home/username/Endless-Sky-Mission-Builder-master/src/model/Mission.py", line 15, in <module>
    from src.model.model_data_parsers import MissionParser
ModuleNotFoundError: No module named 'src'
```
The issue is to be found here:
from model import Mission
from src.gui.GUI import GUI

But the ESMB.py is already in the subfolder 'src'. Not sure on the details, but the way the current dir and its subdirs are searched for modules has changed with different Python version. If this is ok for you, I'll try to fix it, so it should be working with all versions, you may still have to test it afterwards in your pipeline. Anyway i can only test everything on Fedora.

**Comment by MCOfficer** [comment]
as far as i know ESMB doesn't work with python 2 to begin with.

Quoting #22:

> ESMB is only intended to be run from source during development, so use Pycharm for that.

The executable file built on ubuntu should work fine on other linux distros, so you can use that instead.

**Comment by Harald-Berghoff** [comment]
I guess Pycharm does some 'magic' with the current path and the Pythonpath before starting the code (I know Eclipse does this for sure). That still doesn't make the imports to work in other IDEs or on the console without issues. 

Either you start from above src, it would need to be `from src/model import Mission` or you start from with src, it would then need to be `from gui.GUI import GUI`. The easiest way will be to explicitly add the path of ESMB.py to the Pythonpath. This isn't a big deal, I'll send you a PR and you can than decide if you like to include the changes or leave it as is.

**Comment by shitwolfymakes** [comment]
Solved, thank you some much!
